### ISSUE TITLE
1Mhz oscillator added - findings

### ISSUE THREAD

**Issue by bastenhoor** [RobTillaart/AD9833#12]
Hi Rob,

Thanks for all the great libraries for Arduino!

I tried the AD9833 (breakout boeard) and it works great.
I also changed the crystal oscillator from 25Mhz to 1Mhz (really easy with a heatgun on the breakout board).
That also works great!

I used the Low level API functions and perfect results.

I think there is a misstake in the documentation:
it says: void writeFrequencyRegister(uint8_t channel, uint32_t freq) channel = 0 or 1, freq = 0 .. 134217728
But I think 134217728 is only half of the possibilities. The datasheet says 2^28, so 268435456.
I'm using the AD9833 for audio, so I cannot hear if it is correct.
But when I changed to the 1Mhz crystal and applied the fMCLK/2^28 × FREQREG function, my tuner said 440 spot on at writeFrequencyRegister(0, 118112)

Greetings,
Bas

**Comment by RobTillaart** [comment]
> Thanks for all the great libraries for Arduino!

You're welcome

> changed the crystal oscillator from 25Mhz to 1Mhz (really easy with a heatgun on the breakout board).

Is that a desoldering heat gun or a paint stripper alike?
Normally one uses something like cupper desolderstrips e,g, https://www.tinytronics.nl/shop/nl/gereedschap-en-montage/solderen/verbruiksartikelen/desoldeerlint/desoldeerlint-1mm-1.5m

> I think there is a misstake in the documentation:
it says: void writeFrequencyRegister(uint8_t channel, uint32_t freq) channel = 0 or 1, freq = 0 .. 134217728
But I think 134217728 is only half of the possibilities. The datasheet says 2^28, so 268435456.

The code does use the 268435456.0 so indeed a documentation 
```cpp
  uint32_t fr = round(_freq[channel] * (268435456.0 / 25000000.0));

  writeFrequencyRegister(channel, fr);
```

> But when I changed to the 1Mhz crystal and applied the fMCLK/2^28 × FREQREG function, my tuner said 440 spot on at writeFrequencyRegister(0, 118112)

Sounds like a perfect A.

What happens if you use the high level **setFrequency(440);**?
Does it give the expected 440 Hz? I assume it will be factor 25 lower?  17 Hz
Maybe test **setFrequency(440 * 25);** resulting in 440 Hz (A).

----

Anyway, the library should have a means to adjust the frequency of the crystal oscillator.
That would allow you to use the 
- **bool setCrystalFrequency(uint32_t crystal = 25000000)**  
- **uint32_t getCrystalFrequency()** 

Will create a new version today.

**Comment by RobTillaart** [comment]
You're right about the 0 .. 134217728 ==> 0..268435455  (2^28 -1)

**Comment by bastenhoor** [comment]
I used a desoldering heat gun. Because the crystal has it's connections on the back of the package.
I used 400 degrees / 80 windspeed and circeld around. It came of really easy.
Then I cleaned the pads with the solder wick (your link). I added some flux on the solder wick, so the wick sucks in the solder (tin) really easy. Then slowly move away from the pad and they will be clean.
The crystal is a 7050 / 1Mhz
Then I used type 4 solder paste and reheated and perfect!
If you don't have a heatgun, I can send you some modded breakout boards ;-)
________________________________________________________________________________________________

What happens if you use the high level setFrequency(440);?
Does it give the expected 440 Hz? I assume it will be factor 25 lower? 17 Hz
Maybe test setFrequency(440 * 25); resulting in 440 Hz (A).
--> That works as expected
________________________________________________________________________________________________

Anyway, the library should have a means to adjust the frequency of the crystal oscillator.
That would allow you to use the
    bool setCrystalFrequency(uint32_t crystal = 25000000)
    uint32_t getCrystalFrequency()

-->  That would be even easier!

**Comment by RobTillaart** [comment]
@bastenhoor 
Created a develop branch with the two function named above. Build is running so there might be some minor tweaking needed.
What I measured is that the performance of **setFrequency()** dropped from 44 us to 76 us on my UNO. 
That is almost twice as slow, don't know if this is a showstopper for you or other users.
Would still allow to change the frequency 10.000++ times per second, so I expect (hope) it will be OK.

Alternative is to define a **const float crystal factor = 2^28 / crystalfrequency** 
That means modifying the lib and only have a compile time adjustment once.

I prefer to keep the runtime adjustments as it would also allow e.g. temperature compensation of the oscillator.

For now it is an experimental feature and I have to see if it results in problems.

Note to myself: There is also the alternative to create a derived class with the adjustable crystal functions as extra.

**Comment by RobTillaart** [comment]
@bastenhoor 
If you have time can you verify the develop branch? (I have not tested with hardware yet).

**Comment by RobTillaart** [comment]
(thank for your feedback about the soldering gun et al.).

**Comment by RobTillaart** [comment]
Build succeeded, created a PR of the develop branch.
